CREATE TABLE "workdays" (
  "id" SERIAL PRIMARY KEY,
  "hours" FLOAT(2) NOT NULL,
  "downs" TINYINT DEFAULT 0 NOT NULL,
  "tokes" SMALLINT DEFAULT 0 NOT NULL,
  "date" DATE NOT NULL,
  "notes" TEXT,
  "user_id" INTEGER REFERENCES "user"(id)
    ON DELETE CASCADE NOT NULL
);
